// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoDeliverIT.Data;

#nullable disable

namespace ProjetoDeliverIT.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251013223918_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ProjetoDeliverIT.Models.Conta", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTimeOffset>("DataPagamento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("DataVencimento")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DiasAtraso")
                        .HasColumnType("int");

                    b.Property<decimal>("JurosDia")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Multa")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("ValorCorrigido")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ValorOriginal")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("ID");

                    b.ToTable("Contas");
                });

            modelBuilder.Entity("ProjetoDeliverIT.Models.ContaRegraAtraso", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("DiasMaximo")
                        .HasColumnType("int");

                    b.Property<int>("DiasMinimo")
                        .HasColumnType("int");

                    b.Property<decimal>("JurosDia")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Multa")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("ID");

                    b.ToTable("ContaRegraAtrasos");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DiasMaximo = 3,
                            DiasMinimo = 0,
                            JurosDia = 0.1m,
                            Multa = 0.02m
                        },
                        new
                        {
                            ID = 2,
                            DiasMaximo = 5,
                            DiasMinimo = 4,
                            JurosDia = 0.2m,
                            Multa = 0.03m
                        },
                        new
                        {
                            ID = 3,
                            DiasMinimo = 6,
                            JurosDia = 0.3m,
                            Multa = 0.05m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
